### ISSUE TITLE
[Loop Buffer] loop buffer instructions are not inserted in processors without predication

### ISSUE THREAD

**Issue by barrydebruin** [cpc/tce#128]
For processors without predication support i.e. the gcu uses bnz, bz instead of jump + conditional execution, the loop scheduler fails to insert loop buffer operations.

The verbose _tcecc_ output indicates that the loops are found, but somehow it will always fail to insert the loop buffer instructions:

**loop scheduler failed, using basic block scheduler instead**

See a output snippet below:

    ---- LowerMissingInstructions ----
    using 'GM' as the default data address space
    ### compiling (optimized): _start
    ### compiling (optimized): _exit
    ### compiling (optimized): main
    CFG detects single BB loop
    tripcount: 3
    executing loop pass with trip count 3
    LoopScheduler with MinII=1 MaxII=18
    Testing with II=6
    Loop scheduling with epilog,  no conditional prolog(no predication)
    
    Handling new loop ddg: main_1
    Testing with II=18
    Loop scheduling with epilog,  no conditional prolog(no predication)
    
    Handling new loop ddg: main_2
    loop scheduler failed, using basic block scheduler instead
    BB -- inner loop with trip count: 3
    BB -- instruction count: 9
    BB -- move slots used: 17 of 108 (15.7407%)
    DDG height 11
    CFG detects single BB loop
    tripcount: 128
    executing loop pass with trip count 128
    LoopScheduler with MinII=1 MaxII=18
    Testing with II=6
    Loop scheduling with epilog,  no conditional prolog(no predication)

**Comment by pjaaskel** [comment]
(And I believe loop buffer for machines without predication is simply an unimplemented feature.)
