### ISSUE TITLE
Speed up LLVM installation with this one wierd trick

### ISSUE THREAD

**Issue by sarahec** [cpc/tce#138]
The LLVM installation scripts clone the whole repo, which is quite large. Since we only need to build against a specific branch, a shallow clone would check out only what we need: the latest files without their history.

The trick is changing:
```sh
        git clone --branch release/14.x https://github.com/cpc/llvmtce.git $llvm_co_dir\
```

to 
```sh
        git clone --depth=1 --branch release/14.x https://github.com/cpc/llvmtce.git $llvm_co_dir\
```

The latter checks out only 118K objects vs. 4MM for the full repo. On my (admittedly ancient) network, it's about a 30x speedup.

If this is acceptable, I'll submit the PR.

**Comment by pjaaskel** [comment]
Yes a PR very much appreciated. I've thought about this before (and missed the old LLVM svn repo with the centralized history!).
