### ISSUE TITLE
the llvm lib check is faulty 

### ISSUE THREAD

**Issue by jfmherokiller** [cpc/tce#37]
from running many tests i have seen llvm install the dynamic libarary as libllvm(shared library suffix) instead of libllvm-(version number)(shared library suffix)

**Comment by pjaaskel** [comment]
With which cmake flags you get that? At least the TCE's LLVM installer, which uses the -DLLVM_LINK_LLVM_DYLIB=TRUE CMake flag for the LLVM build, installs an .so with the expected naming.
