### ISSUE TITLE
seg. fault for generatebits

### ISSUE THREAD

**Issue by alekob** [cpc/tce#43]
generatebits fails with an segmentation fault when the compressor "InstructionDictionary" is used. Please unpack the attached archive and do a "make idict" 
[generatebits.zip](https://github.com/cpc/tce/files/556738/generatebits.zip)

**Comment by alekob** [comment]
Just for clarification: this issue is not related to the proxim debugger window issue. Its still exists in the latest version!

**Comment by alexhrv** [comment]
Thank you, we are aware of this. Seems like it has something to do with **ensure_programmability**-switch (setting it to **no** doesn't create segfault). The issue is still under investigation

**Comment by linehill** [comment]
The source of the issue has been located and the fix is commited soon after I have tested it.
