### ISSUE TITLE
User manual: LaTeX converting --prefix to -prefix

### ISSUE THREAD

**Issue by pjaaskel** [cpc/tce#53]
The tutorial suggests the following command.

cp $(tce-config -prefix)/share/tce/data/mach/minimal.adf start.adf

**Comment by alexhrv** [comment]
Could not spot the problem in the latest pdf file, both dashes are there:


![dashes](https://cloud.githubusercontent.com/assets/2932113/25997659/aa524474-3725-11e7-8b3d-7e3c49ee0f06.png)

**Comment by pjaaskel** [comment]
Seems to be a problem in the HTML version. http://tce.cs.tut.fi/user_manual/TCE/node10.html#SECTION00411000000000000000

**Comment by linehill** [comment]
Replacing '--'s with '{--}' in the latex doc seems to work for PDF output but not for HTML output (with latex2html).

**Comment by alexhrv** [comment]
Replacing **\shellcmd** and surrounding the commands with **\begin{verbatim}** and **\end{verbatim}** in the latex doc file seems to fix this issue for both pdf and html without the need to escape the '--' characters.

**Comment by pjaaskel** [comment]
OK please commit.
