### ISSUE TITLE
2 compile errors

### ISSUE THREAD

**Issue by postoroniy** [cpc/tce#6]
1) when  llvm 3.6.1 in use error takes place here
src/applibs/LLVMBackend/TCEStubTargeMachine.cc
I got error about tcele target absence
possible fix is below 2 commented out lines:
```c
extern "C" void LLVMInitializeTCETargetInfo() {
    RegisterTarget<Triple::tce, /*HasJIT=*/false>
        X(TheTCETarget, "tce", "TCE custom processor");
    // RegisterTarget<Triple::tcele, false>
    //     Y(TheTCELETarget, "tcele", "TCE custom processor (little endian)");
}
```
2)takes place when downloaded zip file is used for compile without invoking git.
error is here ./src/tools/tce_version_string.h, when compiler tries pick up release version(commit version) for compile and failed since .git/index does not exist.
sorry but I have no solution because I've already cloned git repo and this error didn't appear.

ps. all tests were passed

**Comment by pjaaskel** [comment]
1) should go away if you install your LLVM using the patches shipped with TCE. This is easiest done by using tools/scripts/install_llvm_3.7.sh   2) seems like a real bug although we haven't distributed TCE with packages for a while, the snapshot possibility is there.
