### ISSUE TITLE
tcecc segfaults in case of an unconnected FU

### ISSUE THREAD

**Issue by pjaaskel** [cpc/tce#99]
I accidentally left the REFLECT FU unconnected in TCE tour. tcecc just segfaults in this case (at least when trying to invoke the custom ops via macros). Somewhere in RM construction, I think.

**Comment by Sannoso** [comment]
What would be the right approach to fix this? What is the wanted behavior?
1) Not being able to save an adf with unconnected FUs
2) Allow adfs with unconnected FUs and when running tcecc, throw an error with a clear message instead of a segfault
3) something else?

**Comment by pjaaskel** [comment]
3. just ignore that in RM construction as a resource one can use. But like said, this is not worth looking into at this point when we have more urgent tasks.

**Comment by Sannoso** [comment]
see new pull request with fix https://github.com/cpc/tce/pull/122
